/* General field planning controls with optional Rosette catalogs. Catalog counts are not population or ETC estimates. */
(function(){
'use strict';
const G=SkyGeometry;
const state={geometry:null,data:{},layers:[],maskedLayers:[],hiddenOriginals:new Set(),selected:[],pending:null,ready:false};
const el=id=>document.getElementById(id);
const presets={onc:[83.8186,-5.3897,0,.16],rosette:[97.940875,4.866111,270,.22],deep:[97.98442905121564,4.947611111111112,245,.15]};
const initialCountUI=window.updateFootprintCatalogCountUI;
const oldFootprint=window.updateFootprintRealtime;
const oldClear=window.clearActiveFootprint;
const oldAll=window.getAllCatalogData;
const oldBounds=window.getFootprintExtentDeg;
const oldAxis=window.computeFootprintMajorAxisDeg;
function options(){return {membership:el('rp-membership').value,screen:el('rp-screen').checked,kmin:Number(el('rp-kmin').value),probability:Number(el('rp-probability').value)};}
function rows(){return G.merge(el('rp-deep').checked?(state.data.deep||[]):[],el('rp-wide').checked?(state.data.wide||[]):[]);}
function coordinate(){return ['footprint-ra-slider','footprint-dec-slider','footprint-pa-slider'].map(id=>Number(el(id).value));}
function setPosition(ra,dec,pa){if(!Number.isFinite(ra)||!Number.isFinite(dec)||dec>90||dec< -90)return;ra=(ra%360+360)%360;for(const [id,v] of [['ra',ra],['dec',dec]]){const s=el('footprint-'+id+'-slider');s.min=v-.15;s.max=v+.15;s.step=.0001;s.value=v;el('fp-'+id+'-input').value=v.toFixed(6);}if(pa!==undefined){el('footprint-pa-slider').value=pa;el('fp-pa-input').value=pa;}window.updateFootprintRealtime();}
window.plannerPreset=async function(key){const p=presets[key];el('rp-follow').checked=false;el('footprint-instrument').value='jwst';clearImageOverlay();aladin.gotoRaDec(p[0],p[1]);aladin.setFoV(p[3]);setPosition(...p);el('rp-region').textContent=key==='onc'?'ONC':key==='deep'?'Rosette — deep-field optimum':'Rosette — Roman study center';if(key!=='onc'){el('rp-deep').checked=true;if(key==='rosette')el('rp-wide').checked=true;await loadEnabled();}};
window.centerFootprintOnView=function(){setPosition(...aladin.getRaDec());};
window.updateFootprintRealtime=function(){if(!state.geometry||el('footprint-instrument').value!=='jwst'){oldFootprint();return;}
 const [ra,dec,pa]=coordinate();el('fp-ra-input').value=ra.toFixed(6);el('fp-dec-input').value=dec.toFixed(6);el('fp-pa-input').value=pa.toFixed(2);
 if(activeFootprintOverlay)aladin.removeLayer(activeFootprintOverlay);if(activeFootprintFillOverlay){aladin.removeLayer(activeFootprintFillOverlay);activeFootprintFillOverlay=null;}
 activeFootprintOverlay=A.graphicOverlay({color:selectedColors.footprint,lineWidth:1});aladin.addOverlay(activeFootprintOverlay);
 const polys=G.polygons(state.geometry,ra,dec,pa);jpgOverlayFootprintPolys=[];
 for(const d of polys){const poly=d.points.concat([d.points[0]]);jpgOverlayFootprintPolys.push(poly);activeFootprintOverlay.add(A.polyline(poly,{color:d.channel==='SW'?'#8bb8b0':selectedColors.footprint,lineWidth:d.channel==='SW'?1:2}));if(footprintFillOpacity>0)addFilledPoly(activeFootprintOverlay,poly,selectedColors.footprint,hexToRgba(selectedColors.footprint,footprintFillOpacity));}
 if(el('rp-hide-outside')?.checked)renderCatalogs();else window.updateFootprintCatalogCountUI();};
window.clearActiveFootprint=function(){oldClear();renderCatalogs();renderOtherSources();refreshCounts();};
window.countSourcesInJWSTFootprint=function(data,ra,dec,pa){if(!state.geometry)return 0;return data.filter(G.selector(state.geometry,ra,dec,pa,el('rp-coverage').value)).length;};
window.getAllCatalogData=function(){return oldAll().concat(G.filter(rows(),options()));};
window.updateFootprintCatalogCountUI=function(){initialCountUI();if(state.ready){refreshCounts();renderOtherSources();if(activeFootprintOverlay&&rows().length){el('footprint-count-value').textContent=catalogInFootprintCount.toLocaleString();el('footprint-count-value').classList.remove('empty');}}};
function coverageMessage(polys){const messages=[];if(el('rp-deep').checked){const pts=polys.flatMap(p=>p.points);if(pts.some(p=>p[0]<97.95125||p[0]>98.017334||p[1]<4.903722||p[1]>4.982389))messages.push('Footprint extends beyond the deep catalog field. Its count is a partial-coverage count.');}
 if(el('rp-wide').checked){const center=G.unit(97.940875,4.866111);if(polys.flatMap(p=>p.points).some(p=>{const u=G.unit(...p);return Math.acos(Math.min(1,u.reduce((s,x,i)=>s+x*center[i],0)))*180/Math.PI>35/60;}))messages.push('Footprint extends beyond the 35-arcmin wide-catalog query. Counts outside it are unavailable.');}
 return messages.join(' ');}
function refreshCounts(){const box=el('rp-results');if(!activeFootprintOverlay){box.textContent='Place a footprint to count sources.';state.selected=[];window.plannerIMFMembers=[];document.dispatchEvent(new Event('planner-counts'));return;}if(el('footprint-instrument').value!=='jwst'){box.textContent='Rosette breakdown uses NIRCam. The catalog total above also supports Roman.';state.selected=[];window.plannerIMFMembers=[];document.dispatchEvent(new Event('planner-counts'));return;}if(!state.geometry)return;
 const xyz=coordinate(),all=rows(),inside=all.filter(G.selector(state.geometry,...xyz,el('rp-coverage').value));const selected=G.filter(inside,options());state.selected=selected;window.plannerIMFMembers=inside.filter(r=>r.member==='Y'&&Number.isFinite(r.mass));document.dispatchEvent(new Event('planner-counts')); 
 const counts={selected:selected.length,members:selected.filter(r=>r.member==='Y').length,possible:selected.filter(r=>r.member==='?').length,probable:selected.filter(r=>r.member!=='Y'&&r.probability>=options().probability).length,unknownMass:selected.filter(r=>!Number.isFinite(r.mass)).length};
 box.innerHTML='<strong>'+counts.selected.toLocaleString()+(options().membership==='all'?' catalog sources; not a member count':' selected members / candidates')+'</strong><div>'+inside.length.toLocaleString()+' geometric matches before selection</div><dl><dt>Published members (Y)</dt><dd>'+counts.members+'</dd><dt>Possible members (?)</dt><dd>'+counts.possible+'</dd><dt>Other high-probability candidates*</dt><dd>'+counts.probable+'</dd><dt>Mass unavailable</dt><dd>'+counts.unknownMass+'</dd></dl><div class="rp-note">*Probability and possible-member categories can overlap.</div>';
 const bins=[[0,.02],[.02,.04],[.04,.075],[.075,.15],[.15,.3],[.3,Infinity]];el('rp-masses').innerHTML='<summary>Published mass bins</summary><table><tr><th>Solar masses</th><th>Selected</th></tr>'+bins.map(([a,b])=>'<tr><td>'+a+'–'+(b===Infinity?'above':b)+'</td><td>'+selected.filter(r=>Number.isFinite(r.mass)&&r.mass>=a&&r.mass<b).length+'</td></tr>').join('')+'</table><p class="rp-note">Published masses retain the original study ages; they are not a common 10-Myr inference.</p>';
 el('rp-coverage-note').textContent=coverageMessage(G.polygons(state.geometry,...xyz));el('rp-export').disabled=!selected.length;}

window.plannerSourceVisible=function(r){if(!el('rp-hide-outside')?.checked||!activeFootprintOverlay)return true;const xyz=coordinate();return el('footprint-instrument').value==='jwst'?!!state.geometry&&G.selector(state.geometry,...xyz,el('rp-coverage').value)(r):countSourcesInRomanFootprintFast([r],...xyz)>0;};
function displayRows(){return G.filter(rows(),options()).filter(window.plannerSourceVisible);}
function renderOtherSources(){
 for(const l of state.maskedLayers)aladin.removeLayer(l);state.maskedLayers=[];
 const items=loadedCatalogs.map(c=>({original:c.aladinCat,data:c.data,color:c.color,shape:c.shape,name:c.name})).concat(sources.filter(s=>s.catalog).map(s=>({original:s.catalog,data:[s],color:s.color,name:s.name})));
 const active=new Set(items.map(x=>x.original));
 for(const original of state.hiddenOriginals)if(!active.has(original))state.hiddenOriginals.delete(original);
 if(!el('rp-hide-outside')?.checked||!activeFootprintOverlay){for(const original of state.hiddenOriginals)aladin.addCatalog(original);state.hiddenOriginals.clear();return;}
 for(const item of items){if(!state.hiddenOriginals.has(item.original)){aladin.removeLayer(item.original);state.hiddenOriginals.add(item.original);}const subset=item.data.filter(window.plannerSourceVisible);if(!subset.length)continue;const cat=A.catalog({name:item.name||'Sources in footprint',color:item.color||'#e6edf3',shape:item.shape||'circle',sourceSize:10,onClick:'showTable'});cat.addSources(subset.map(r=>A.source(r.ra,r.dec,r)));aladin.addCatalog(cat);state.maskedLayers.push(cat);}
}

function massColor(r){if(!Number.isFinite(r.mass))return '#e6edf3';return r.mass<.02?'#a084b4':r.mass<.04?'#89a6bc':r.mass<.075?'#63a796':r.mass<.15?'#c9a66c':'#cc896e';}
function renderCatalogs(){for(const l of state.layers)aladin.removeLayer(l);state.layers=[];const groups=new Map();for(const r of displayRows()){const shape=r.member==='?'?'square':'circle';const key=massColor(r)+'|'+shape;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}
 for(const [key,data] of groups){const [color,shape]=key.split('|');const cat=A.catalog({name:'Rosette '+(shape==='square'?'possible members':'sources'),color,shape,sourceSize:10,onClick:'showTable'});cat.addSources(data.map(r=>A.source(r.ra,r.dec,{name:r.id,K:r.K,member:r.member||'not assessed',membership_probability:r.probability,mass_solar:r.mass,spectral_type:r.spectralType})));aladin.addCatalog(cat);state.layers.push(cat);}
 updateCatalogListUI();updateFootprintCatalogCountUI();}
async function loadEnabled(){el('rp-load-status').textContent='Loading catalog snapshots…';try{await Promise.all(['deep','wide'].filter(k=>el('rp-'+k).checked&&!state.data[k]).map(async k=>{const response=await fetch('skyplanner-rosette-'+k+'.json');if(!response.ok)throw new Error(k+' catalog: HTTP '+response.status);state.data[k]=await response.json();state.data[k].forEach(r=>r.unit=G.unit(r.ra,r.dec));}));el('rp-load-status').textContent=['deep','wide'].filter(k=>el('rp-'+k).checked).map(k=>(state.data[k]||[]).length.toLocaleString()+' '+k+' rows').join('; ')||'No Rosette catalog enabled.';renderCatalogs();}catch(e){el('rp-load-status').textContent='Catalog load failed: '+e.message;}}
function exportRows(){const keys=['id','ra','dec','member','probability','mass','K','J','H','Av','spectralType'];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const text=keys.join(',')+'\n'+state.selected.map(r=>keys.map(k=>quote(r[k])).join(',')).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='rosette-selected-'+coordinate().map(x=>x.toFixed(4)).join('_')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const oldDraw=window.drawOverlayMarkers;window.drawOverlayMarkers=function(ctx,w,h,scale=1){oldDraw(...arguments);for(const r of displayRows()){const pix=aladin.world2pix(r.ra,r.dec);if(!pix||pix[0]<0||pix[0]>w||pix[1]<0||pix[1]>h)continue;ctx.strokeStyle=massColor(r);ctx.lineWidth=1.5*scale;ctx.beginPath();ctx.arc(pix[0]*scale,pix[1]*scale,4*scale,0,2*Math.PI);ctx.stroke();}};
// Use actual detector corners in PNG framing, rather than the old square approximation.
window.getFootprintExtentDeg=function(ra,dec,pa,instrument){if(instrument!=='jwst'||!state.geometry)return oldBounds(...arguments);const pts=G.polygons(state.geometry,ra,dec,pa).flatMap(x=>x.points).map(p=>skyToOffsetDeg(...p,ra,dec));return 2*Math.max(...pts.flat().map(Math.abs));};
window.computeFootprintMajorAxisDeg=function(ra,dec,pa,instrument){if(instrument!=='jwst'||!state.geometry)return oldAxis(...arguments);const pts=G.polygons(state.geometry,ra,dec,pa).flatMap(x=>x.points).map(p=>aladin.world2pix(...p)).filter(Boolean);const cx=pts.reduce((s,p)=>s+p[0],0)/pts.length,cy=pts.reduce((s,p)=>s+p[1],0)/pts.length;let xx=0,yy=0,xy=0;pts.forEach(p=>{xx+=(p[0]-cx)**2;yy+=(p[1]-cy)**2;xy+=(p[0]-cx)*(p[1]-cy);});return .5*Math.atan2(2*xy,xx-yy)*180/Math.PI;};


const oldList=window.updateCatalogListUI;
window.updateCatalogListUI=function(){oldList();const n=rows().length;if(!n)return;if(!loadedCatalogs.length)el('catalog-list').innerHTML='';const note=document.createElement('div');note.className='rp-note';note.textContent=n.toLocaleString()+' matched Rosette rows loaded (selection controls above)';el('catalog-list').append(note);el('total-sources-value').textContent=(getTotalCatalogCount()+n).toLocaleString();el('total-sources-value').classList.remove('empty');};
const oldClearCatalogs=window.clearAllCatalogs;window.clearAllCatalogs=function(){el('rp-deep').checked=false;el('rp-wide').checked=false;for(const l of state.layers)aladin.removeLayer(l);state.layers=[];el('rp-load-status').textContent='No Rosette catalog enabled.';oldClearCatalogs();};
const oldCrop=window.computeFootprintBoundsInRotatedCanvas;window.computeFootprintBoundsInRotatedCanvas=function(w,h,rw,rh,scale,angle){if(el('footprint-instrument').value!=='jwst'||!state.geometry)return oldCrop(...arguments);const a=angle*Math.PI/180,pts=G.polygons(state.geometry,...coordinate()).flatMap(d=>d.points).map(p=>aladin.world2pix(...p)).filter(Boolean).map(p=>{const x=p[0]*scale-w/2,y=p[1]*scale-h/2;return [rw/2+x*Math.cos(a)-y*Math.sin(a),rh/2+x*Math.sin(a)+y*Math.cos(a)];});if(!pts.length)return null;return {minX:Math.floor(Math.min(...pts.map(p=>p[0]))),minY:Math.floor(Math.min(...pts.map(p=>p[1]))),maxX:Math.ceil(Math.max(...pts.map(p=>p[0]))),maxY:Math.ceil(Math.max(...pts.map(p=>p[1])))};};

function initCatalogPresets(){
 const parent=el('panel-catalog').querySelector('.panel-content');const wrap=document.createElement('div');wrap.innerHTML=`<label for="catalog-preset">Catalog presets</label><select id="catalog-preset"><optgroup label="Rosette / NGC 2244"><option value="rosette_phot">Rosette — deep NIR photometry (Mužić 2019)</option><option value="rosette_members">Rosette — membership + masses (Almendros-Abad 2023)</option><option value="rosette_wide">Rosette — Gaia membership probabilities (Mužić 2022)</option></optgroup><optgroup label="ONC"><option value="coup">ONC — COUP (Getman 2005)</option><option value="kim">ONC — Kim 2019 proper motions</option></optgroup><optgroup label="Other fields"><option value="cra">CrA substellar catalog</option><option value="sgr">Sagittarius stream</option></optgroup></select><button id="load-catalog-preset">Load selected catalog</button><p class="rp-note">Rosette presets share matched IDs, preserving membership and masses without duplicate counting. Use the Rosette button above to move the view.</p>`;parent.prepend(wrap);
 el('load-catalog-preset').onclick=async()=>{const key=el('catalog-preset').value;if(!key.startsWith('rosette')){loadPresetCatalog(key);return;}if(key==='rosette_wide'){el('rp-wide').checked=true;el('rp-membership').value='probable';}else{el('rp-deep').checked=true;el('rp-membership').value=key==='rosette_members'?'members':'all';}await loadEnabled();};
 const oldPast=window.updatePastVizierDatalist;window.updatePastVizierDatalist=function(){oldPast();for(const [id,name] of [['J/ApJ/881/79/table2','Rosette deep NIR'],['J/A+A/677/A26/tabled1','Rosette membership'],['J/A+A/677/A26/table2','Rosette masses'],['J/A+A/668/A19/catalog','Rosette probabilities']]){const option=document.createElement('option');option.value=id;option.label=name;el('past-vizier-tables').append(option);}};updatePastVizierDatalist();
}
const originalOptimize=window.findOptimalOrientation;
window.findOptimalOrientation=async function(){if(el('footprint-instrument').value!=='jwst')return originalOptimize();const data=getAllCatalogData();if(!data.length){showToast('Load a catalog and select sources first.','error');return;}const [ra,dec,pa]=coordinate();let best={pa,count:countSourcesInJWSTFootprint(data,ra,dec,pa)};el('optimize-btn').disabled=true;try{for(let a=0;a<360;a+=5){const count=countSourcesInJWSTFootprint(data,ra,dec,a);if(count>best.count)best={pa:a,count};el('optimize-status').textContent='Testing V3 PA '+a+' degrees…';await new Promise(resolve=>setTimeout(resolve,0));}const start=best.pa;for(let a=start-5;a<=start+5;a++){const angle=(a+360)%360,count=countSourcesInJWSTFootprint(data,ra,dec,angle);if(count>best.count)best={pa:angle,count};}setPosition(ra,dec,best.pa);el('optimize-status').textContent='Best roll at this center: '+best.pa+'°; '+best.count+' selected sources. Visibility not checked.';}finally{el('optimize-btn').disabled=false;}};

A.init.then(async function(){
 const panel=document.createElement('section');panel.className='panel rp-panel';panel.innerHTML=`<div class="panel-header">Field planning</div><div class="panel-content">
 <div class="coord-row"><button id="rp-onc">ONC</button><button id="rp-rosette">Rosette</button></div><button id="rp-optimum" class="btn-secondary">Rosette deep-field optimum</button><p id="rp-region" class="rp-note">ONC</p>
 <label class="rp-check"><input type="checkbox" id="rp-follow"> Move footprint when I pan the sky</label><label class="rp-check"><input type="checkbox" id="rp-click"> Click sky to place footprint</label>
 <label class="rp-check"><input type="checkbox" id="rp-hide-outside"> Hide sources outside footprint (map + PNG)</label><hr><label class="rp-check"><input type="checkbox" id="rp-deep"> Deep NIR + published membership/masses</label><label class="rp-check"><input type="checkbox" id="rp-wide"> Wider Gaia membership probabilities</label><p id="rp-load-status" class="rp-note" role="status">No Rosette catalog enabled.</p>
 <label for="rp-membership">Count and display</label><select id="rp-membership"><option value="members">Published members (Y)</option><option value="possible">Members + possible members</option><option value="probable">Members + high-probability candidates</option><option value="all" selected>All catalog sources</option></select>
 <label for="rp-probability">Minimum membership probability</label><input id="rp-probability" type="number" min="0" max="1" step="0.05" value="0.8">
 <label class="rp-check"><input type="checkbox" id="rp-screen" checked> Apply bright-limit proxy</label><label for="rp-kmin">Minimum K magnitude (Vega)</label><input type="number" id="rp-kmin" min="0" max="35" step="0.1" value="15.8964139349"><p class="rp-note">Fainter sources have larger magnitudes. This adjustable K proxy is not a source-specific ETC saturation limit. Missing K is excluded when enabled.</p>
 <label for="rp-coverage">NIRCam coverage</label><select id="rp-coverage"><option value="joint">Simultaneous SW and LW</option><option value="SW">SW only</option><option value="LW">LW only</option></select>
 <div id="rp-results" aria-live="polite">Loading detector geometry…</div><details id="rp-masses"></details><p id="rp-coverage-note" role="status"></p><button id="rp-export" disabled>Export selected sources CSV</button>
 <details><summary>Catalogs and geometry</summary><p class="rp-note">Mužić 2019 deep imaging (793 sources), joined to Almendros-Abad 2023 membership and masses. Mužić 2022 probabilistic catalog within 35 arcmin of the Roman-study Rosette center. Matches within 1 arcsec count once, with deep photometry and published membership preferred. Unknown masses have pale silver outlines; possible members are squares.</p><a href="https://cdsarc.cds.unistra.fr/viz-bin/cat/J/A+A/677/A26" target="_blank" rel="noopener">Membership catalog</a> · <a href="https://cdsarc.cds.unistra.fr/viz-bin/cat/J/A+A/668/A19" target="_blank" rel="noopener">Wide catalog</a><p class="rp-note">NRCALL_FULL, SIAF PRDOPSSOC-065. Solid LW and thinner SW detector outlines. V3 PA is not detector-edge PA. Planning geometry is not APT scheduling validation.</p></details></div>`;
 document.querySelector('.sidebar').prepend(panel);el('panel-footprints').classList.remove('collapsed');panel.querySelector('hr').before(el('panel-footprints'));initCatalogPresets();
 const apply=document.createElement('button');apply.textContent='Apply entered coordinates';apply.id='rp-apply';el('panel-footprints').querySelector('.panel-content').append(apply);apply.onclick=()=>setPosition(Number(el('fp-ra-input').value),Number(el('fp-dec-input').value),Number(el('fp-pa-input').value));el('footprint-instrument').addEventListener('change',()=>window.updateFootprintRealtime());
 el('rp-onc').onclick=()=>plannerPreset('onc');el('rp-rosette').onclick=()=>plannerPreset('rosette');el('rp-optimum').onclick=()=>plannerPreset('deep');
 for(const k of ['deep','wide'])el('rp-'+k).onchange=loadEnabled;
 for(const k of ['membership','screen','kmin','probability'])el('rp-'+k).onchange=()=>{const o=options();if(!Number.isFinite(o.kmin)||!Number.isFinite(o.probability)||o.probability<0||o.probability>1){el('rp-load-status').textContent='Enter a valid K limit and probability between 0 and 1.';return;}renderCatalogs();};el('rp-hide-outside').onchange=()=>renderCatalogs();el('rp-coverage').onchange=()=>renderCatalogs();el('rp-export').onclick=exportRows;
 aladin.on('positionChanged',p=>{if(el('rp-follow').checked){cancelAnimationFrame(state.pending);state.pending=requestAnimationFrame(()=>setPosition(p.ra,p.dec));}});aladin.on('click',p=>{if(el('rp-click').checked&&p&&Number.isFinite(p.ra)&&Number.isFinite(p.dec))setPosition(p.ra,p.dec);});
 try{const r=await fetch('skyplanner-nircam-siaf.json');if(!r.ok)throw Error('HTTP '+r.status);state.geometry=await r.json();state.ready=true;aladin.setFoV(.16);el('footprint-instrument').value='jwst';selectedColors.footprint='#c5aa73';setPosition(ONC_RA,ONC_DEC,0);el('rp-results').textContent='Choose Rosette to load its catalogs.';}catch(e){el('rp-results').textContent='Detector geometry unavailable: '+e.message;}
});
})();
