/* Optional population scenarios; never added to catalog counts. */
(function(){
'use strict';
const E=id=>document.getElementById('imf-'+id);let grids,report;
function density(m,alpha){return m<.08?Math.pow(m/.08,-alpha):m<.5?Math.pow(m/.08,-1.3):Math.pow(.5/.08,-1.3)*Math.pow(m/.5,-2.3);}
function integrate(lo,hi,alpha,predicate=()=>true){let sum=0;const n=1600,step=Math.log(hi/lo)/n;for(let i=0;i<n;i++){const a=lo*Math.exp(step*i),b=lo*Math.exp(step*(i+1)),m=Math.sqrt(a*b);if(predicate(m))sum+=density(m,alpha)*(b-a);}return sum;}
function magnitude(m,g){if(m<g[0][0]||m>g[g.length-1][0])return NaN;for(let i=1;i<g.length;i++)if(m<=g[i][0]){const a=g[i-1],b=g[i],f=Math.log(m/a[0])/Math.log(b[0]/a[0]);return a[1]+f*(b[1]-a[1]);}return g[g.length-1][1];}
function settings(){return Object.fromEntries(['n','lo','hi','complete','age','distance','av','ext','bright','faint','alpha'].map(k=>[k,Number(E(k).value)]));}
function update(){if(!grids)return;const o=settings();report=null;E('export').disabled=true;
 if(Object.values(o).some(x=>!Number.isFinite(x))||o.n<0||o.lo<.01||o.hi>1.4||o.hi<=o.lo||o.complete<=0||o.complete>1||o.distance<=0||o.av<0||o.ext<0||o.faint<=o.bright){E('result').textContent='Enter valid values: 0.01 ≤ normalization mass < upper mass ≤ 1.4, completeness > 0 and ≤ 1, positive distance, and faint magnitude > bright magnitude.';return;}
 const known=window.plannerIMFMembers||[],g=grids[String(o.age)],dm=5*Math.log10(o.distance/10),norm=(o.n/o.complete)/integrate(o.lo,o.hi,o.alpha),edges=[.01,.02,.04,.075,.15,.3,.5,1.4];
 const result=edges.slice(0,-1).map((lo,i)=>{const hi=edges[i+1],count=norm*integrate(lo,hi,o.alpha),inWindow=norm*integrate(lo,hi,o.alpha,m=>{const mag=magnitude(m,g)+dm+o.ext*o.av;return mag>=o.bright&&mag<=o.faint;}),observed=known.filter(r=>r.mass>=lo&&r.mass<hi).length;return {lo,hi,expected:count,catalogKnownMassMembers:observed,excess:Math.max(0,count-observed),withinMagnitudeWindow:inWindow,brightF250M:magnitude(hi,g)+dm+o.ext*o.av,faintF250M:magnitude(lo,g)+dm+o.ext*o.av};});
 const total=result.reduce((s,r)=>s+r.withinMagnitudeWindow,0);E('result').innerHTML='<strong>'+total.toFixed(1)+' expected objects in the chosen F250M window</strong><p class="rp-note">Conditional population expectation, not a measured source count or a transit yield. A partial catalog footprint cannot establish its own completeness. Decimals represent expected numbers.</p><div style="overflow-x:auto"><table><tr><th>Mass (M☉)</th><th>IMF total</th><th>Known*</th><th>Excess*</th><th>In mag window</th><th>F250M range</th></tr>'+result.map(r=>'<tr><td>'+r.lo+'–'+r.hi+'</td><td>'+r.expected.toFixed(1)+'</td><td>'+r.catalogKnownMassMembers+'</td><td>'+r.excess.toFixed(1)+'</td><td>'+r.withinMagnitudeWindow.toFixed(1)+'</td><td>'+r.brightF250M.toFixed(1)+'–'+r.faintF250M.toFixed(1)+'</td></tr>').join('')+'</table></div><p class="rp-note">*Known = published members with masses in this footprint, before the K brightness filter. Excess = max(IMF total − known, 0); massless catalog members may already account for some of this excess, so it is not a confirmed count of unseen objects. Original catalog ages differ from this model age.</p>';
 E('anchor').textContent=known.filter(r=>r.mass>=o.lo&&r.mass<o.hi).length+' published, mass-characterized members in the normalization interval in the current footprint. Spectroscopic completeness is not known.';
 report={catalogCoverageWarning:document.getElementById('rp-coverage-note').textContent,assumptions:o,normalization:norm,footprint:{ra:Number(document.getElementById('footprint-ra-slider').value),dec:Number(document.getElementById('footprint-dec-slider').value),v3pa:Number(document.getElementById('footprint-pa-slider').value),coverage:document.getElementById('rp-coverage').value},massBins:result,totalInMagnitudeWindow:total,method:'Continuous Kroupa-like dN/dM, slopes alphaBD / 1.3 / 2.3, breaks 0.08 / 0.5 solar masses; BHAC15 F250Mab Vega November 2016 passbands; log-mass interpolation; single age and extinction; no binary or disk correction',caution:'Conditional approximation. Catalog coverage and membership/mass completeness are incomplete. Excess is not a verified unseen population.'};E('export').disabled=false;
}
A.init.then(async()=>{const p=document.createElement('section');p.className='panel rp-panel';p.innerHTML=`<details><summary class="panel-header">Optional IMF population estimate</summary><div class="panel-content"><p class="rp-note">Rosette starting values; editable for other fields. Normalize to a membership-corrected sample in the same sky area and a mass interval where completeness can be estimated. This panel does not change the catalog count.</p>
<label for="imf-n">Observed members in normalization interval</label><input id="imf-n" type="number" min="0" value="0"><button id="imf-use">Use current footprint's mass-characterized members</button><p id="imf-anchor" class="rp-note"></p>
<label for="imf-lo">Normalization lower mass (M☉)</label><input id="imf-lo" type="number" value="0.15" step="0.01"><label for="imf-hi">Normalization upper mass (M☉)</label><input id="imf-hi" type="number" value="0.5" step="0.01"><label for="imf-complete">Assumed completeness fraction</label><input id="imf-complete" type="number" value="1" min="0.01" max="1" step="0.05"><p class="rp-note">1 is a scenario, not measured completeness. Count includes bright members even if they saturate NIRCam. Moving the footprint updates Known; click the button again to renormalize.</p>
<label for="imf-age">Single-age scenario (Myr)</label><select id="imf-age">${[.5,1,2,3,4,5,8,10].map(x=>'<option '+(x===10?'selected':'')+'>'+x+'</option>').join('')}</select><label for="imf-distance">Distance (pc)</label><input id="imf-distance" type="number" value="1500"><label for="imf-av">Visual extinction Aᵥ (mag)</label><input id="imf-av" type="number" value="2" min="0" step="0.5"><label for="imf-ext">A(F250M) / Aᵥ (assumed)</label><input id="imf-ext" type="number" value="0.09" min="0" step="0.01">
<label for="imf-bright">Bright boundary F250M (Vega)</label><input id="imf-bright" type="number" value="16" step="0.1"><label for="imf-faint">Faint boundary F250M (Vega)</label><input id="imf-faint" type="number" value="24" step="0.1"><p class="rp-note">Illustrative magnitude window, not an ETC limit. Larger magnitudes are fainter. Try ages 0.5–10 Myr and Aᵥ = 0–4; higher extinction is a separate sensitivity case.</p><label for="imf-alpha">Substellar IMF slope α below 0.08 M☉</label><input id="imf-alpha" type="number" value="0.3" step="0.1"><p class="rp-note">dN/dM ∝ M⁻α; try −0.4 to 1.0 as slope sensitivity. Assumes one continuous IMF into brown dwarfs and no mass-dependent spatial segregation. It does not infer satellite occurrence rates.</p>
<div id="imf-result" aria-live="polite">Loading models…</div><button id="imf-export" disabled>Export assumptions and mass bins JSON</button><p class="rp-note">N(bin) = N(anchor) / completeness × IMF integral(bin) / IMF integral(anchor). No mass extrapolation below the model grid's 0.01 M☉. BHAC15 synthetic F250M magnitudes use older filter curves; suitable for approximate populations, not source-specific ETC predictions. Extinction is a single adjustable screen; binaries, disks and differential extinction are omitted.</p><a href="https://perso.ens-lyon.fr/isabelle.baraffe/BHAC15dir/BHAC15_iso.JWST" target="_blank" rel="noopener">BHAC15 model grid</a> · <a href="https://doi.org/10.1046/j.1365-8711.2001.04022.x" target="_blank" rel="noopener">Kroupa (2001)</a></div></details>`;
 document.querySelector('.sidebar').append(p);for(const x of p.querySelectorAll('input,select'))x.addEventListener('input',update);
 E('use').onclick=()=>{const o=settings();E('n').value=(window.plannerIMFMembers||[]).filter(r=>r.mass>=o.lo&&r.mass<o.hi).length;update();};document.addEventListener('planner-counts',update);
 E('export').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='imf-population-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 try{const r=await fetch('skyplanner-bhac15-f250m.json');if(!r.ok)throw Error('HTTP '+r.status);const raw=await r.json();grids=Object.fromEntries(Object.entries(raw).map(([k,v])=>[String(Number(k)),v]));update();}catch(e){E('result').textContent='Model load failed: '+e.message;}
});
})();
